### ISSUE TITLE
Black Screen @ The Hub In Quantum.

### ISSUE THREAD

**Issue by 1st-BrainStormer** [kasenvr/project-athena#372] opened 2020-05-19 19:04 UTC
I get a blank screen @ the hub.  Seems to only happening when render method is deferred. if set to forward, everything renders

**Comment by 1st-BrainStormer** [comment] 2020-05-19 19:27
Restarted, issue went away.  When it was happening I could go to another domain and see everything and come back to a blank screen.

**Comment by kasenvr** [comment] 2020-06-14 19:09
Is it a black screen or black portions of the screen that you can look away from? Because this is a known bug that's been in the HiFi code for some time but no one has been able to really tackle yet because we have not figured out how to repro it.

**Comment by 1st-BrainStormer** [comment] 2020-06-15 04:34
Couldn't look away from it. it was black everywhere
it only happened a few times. I reloaded the content and I think that's what fixed it.  But i think is likely a corrupted cache file. When it was happening, everything would start rendering and near the end of everything loading, the whole screen went blank.

**Comment by daleglass** [comment] 2020-07-18 18:58
We considered this during a meeting, and are closing it for now due to the lack of ability to reproduce it.

Please re-open if you can find at least some part of the system to blame and to test: is it a caching issue, a rendering issue, etc? Reproduction would be very helpful.

**Closed by daleglass** 2020-07-18 18:58 UTC
