### ISSUE TITLE
Support for Mouse Look and WASD Movement

### ISSUE THREAD

**Issue by HeadClot** [kasenvr/project-athena#662] opened 2020-08-29 19:36 UTC
Currently user movement in Vircadia is a bit of a pain for people who are used to First Person Shooters that were made post half life or Quake like myself.

The Problem: 
Currently we need to hold down the right mouse button to look around with the mouse. This is really non-standard behavior compared to other 3d First Person Applications.

Q and E strafes left and right.
A and D rotates left and right

How it should be:

A and D should be strafe left and right.

Introduce a mouse look mode where the cursor is locked to the center of the screen and can be unlocked by pressing a toggle button on the keyboard such as the Alt key. We can use the mouse look mode to rotate the users avatar so we do not need to rely on the rotation keys.

**Comment by kasenvr** [comment] 2020-08-29 19:37
You're speaking my language. @HifiExperiments and I are working on a solution for exactly this. :)

**Comment by HeadClot** [comment] 2020-08-29 19:39
> You're speaking my language. @HifiExperiments and I are working on a solution for exactly this. :)

This is good to hear that this is currently being worked on :)

**Comment by JulianGro** [comment] 2020-08-31 01:59
I don't think we ever talked about the WASD controls. Personally I didn't even know that Q and E strafe.

This is the second duplicate request for catching the mouse however, so that is definetly on the list of what a good amount of people want: #321

**Comment by HifiExperiments** [comment] 2020-09-02 18:31
I'm going to close this as a duplicate of #321, we can move discussion there or to the PR I'm about to open

**Closed by HifiExperiments** 2020-09-02 18:31 UTC
Labels: confirmed, enhancement
