### ISSUE TITLE
Feature Request - copying an entity with .001 naming scheme names the new entity .002, and so on...

### ISSUE THREAD

**Issue by Aitolda** [kasenvr/project-athena#575] opened 2020-07-27 03:35 UTC
This is handy when you went to drag/copy multiple entities.  For example entities set to render with zone.  In my test.  I have zone.001, box.001, Material.001 which are all parented to the hiarchy.  If I drag and copy the new entities will have the same name as the original currently.

**Comment by HifiExperiments** [comment] 2020-07-30 01:12
I think one danger here is that if there are attached scripts that rely on things being named specific names, those will break on the duplicated objects

**Comment by Aitolda** [comment] 2020-07-30 03:17
> I think one danger here is that if there are attached scripts that rely on things being named specific names, those will break on the duplicated objects

Hmm...  I wonder what might be a good alternative.

**Comment by kasenvr** [comment] 2020-07-30 03:19
If it's liable to be useful to a great majority of people, simple optional parameters/controls would do.

**Comment by Aitolda** [comment] 2020-07-30 15:59
> If it's liable to be useful to a great majority of people, simple optional parameters/controls would do.

The main thing is to be able to visually distinguish different models in the entity list when duplicates are made.  What I proposed is how it works in blender, but HFExperiments brought up a valid point.  I feel something still needs to indicate these differences, but I guess the question is which issue will we run into more, and is there an alternative?

**Comment by AleziaKurdis** [comment] 2020-08-04 02:00
> I think one danger here is that if there are attached scripts that rely on things being named specific names, those will break on the duplicated objects

After duplication, a script can also be in problem because there are 2 entities with the same name. Duplicates can always generate such undesired consequences, with or without a name change.
To have used duplicate often, I can tell you that  it's annoying to have to check the id to figure which one is the duplicate (to avoid issues with parenting for example)
Plus, you can always rename it directly in the list to remove the duplication mark, which is already easier than now, where you need to figure which one is the copy in order to rename it.

**Comment by HifiExperiments** [comment] 2020-08-04 19:35
that’s a great point.  in that case, I think this should be solved in the create script itself, and I’d vote for append “(number)“ instead of trying to detect a specific naming scheme and modifying it.

so “Box” would have a duplicate “Box (2)” which would have a duplicate “Box (3)”

if there’s an option to toggle the behavior within the create UI, even better

**Comment by Aitolda** [comment] 2020-08-04 19:40
> that’s a great point. in that case, I think this should be solved in the create script itself, and I’d vote for appending “(number)“ instead of trying to detect a specific naming scheme and modifying it.
> 
> so “Box” would have a duplicate “Box (2)” which would have a duplicate “Box (3)”
> 
> if there’s an option to toggle the behavior within the create UI, even better

As long as it's consistent between sessions, this seems adequate.  Ideally the entity list would also sort this as well.

**Comment by AleziaKurdis** [comment] 2020-08-06 03:42
I've just made a first try.

I take the original Entity name 
I loop to trying the name with an appended increment (n)
until I get a unique name.

This is working for Duplicate (CTRL + Move) and Copy-Paste

If you do:
Duplicate "**Box**", you get "**Box (2**)"
if you duplicate "**Box**" another time, you will get "**Box (3)**" (and so on...)
**But if you duplicate "Box (2)"**, you will get "**Box (2) (2)**" which is less interesting already.
I have considered ignoring the appended part so I would have got "**Box (4)**"... which is more elegant, but wrong since "**Box (2)**" is now a fully unique entity (that might have been modified in between). And using "**Box (4)**" would wrongly let you think that it's another duplicate from "**Box**".

![image](https://user-images.githubusercontent.com/60075796/89487812-680bbf80-d774-11ea-895d-e19f907d0bc8.png)
Any suggestions?
"**Box (2.2)**" instead of "**Box (2) (2)**" ?
Other ideas?

**Comment by Aitolda** [comment] 2020-08-06 05:46
> I have considered ignoring the appended part so I would have got "**Box (4)**"... which is more elegant, but wrong since...

I see what your are saying, although I think thing my preference would still be for Box (2) (2) to simply be Box (4) or whatever number is available.  I can appreciate what you were trying to do, but I worry this will be confusing.  Needs more thought.

**Comment by HifiExperiments** [comment] 2020-08-06 06:22
Personally I kinda feel like it should ignore other things around it and just increment whatever is copied.  Say you’ve got a stack of boxes all named “Box”, and you copied them, wouldn’t you expect a stack of boxes all named “Box (2)”?

File systems handle this by not letting you name things with duplicate names, but I wonder how other software does it?

Otherwise I would vote for “Box (4)” to keep it simple

**Comment by AleziaKurdis** [comment] 2020-08-07 02:41
I went with to the "Box (4)" solution.
I simply remove the suffix before appending the next number that would make the name unique.
This is similar to how windows10 manages the incremental suffix when you copy folders.

**Comment by JulianGro** [comment] 2020-09-08 21:27
This can be closed now, right?

**Closed** 2020-09-09 16:25 UTC
Labels: enhancement
