### ISSUE TITLE
Audio device lists often empty firsrt time into HMD mode with Windows MR

### ISSUE THREAD

**Issue by ctrlaltdavid** [kasenvr/project-athena#165] opened 2020-02-10 01:40 UTC
Kalila regularly encounters this problem with Vive.
ctrlaltdavid can't repro with Oculus.

Repro on Windows MR + SteamVR:
- Start Interface.
- Switch to HMD mode.
- Open the tablet and look at the Settings > Audio.
- There are no input or output audio devices listed in either desktop or HMD tabs.
- The program log gets spammed with "length mismatch" error messages.

![desktop](https://user-images.githubusercontent.com/7455448/74115223-f31b5b00-4c12-11ea-839f-b30b03cc3a24.png)

![hmd](https://user-images.githubusercontent.com/7455448/74115227-f6aee200-4c12-11ea-9441-bf273f4c45ab.png)

Repeated program log entry:
```
[WARNING] [default] AudioDeviceList scripting::AudioInputDeviceList::onPeakValueListChanged length mismatch
```
Generated in:
```
void AudioInputDeviceList::onPeakValueListChanged(const QList<float>& peakValueList) {
```

**Comment by kasenvr** [comment] 2020-02-28 07:02
This appears to be a SteamVR bug in general.

**Comment by NathanAdored** [comment] 2020-05-04 22:16
It is doing this to me in the regular Project Athena v0.86.0 K2 interface.  I have to launch and quit and launch and quit and launch again before it finally shows devices in Audio Devices and in Output Devices, and for the duration I can't hear voice in world.  Also, something seems to be slowing Windows 10 down while I'm in Interface, to the point that sometimes Taskbar doesn't react when I mouse over it, and when I'm typing stuff in the Chat window in Interface, what I'm typing does not show up in real time.

**Comment by odysseus654** [comment] 2020-05-17 01:13
If we're not able to repro then I'm guessing we need to gather more information about the problem.  I'm guessing that minidumping this to Sentry would not be a great idea (I'm thinking that would intentionally crash the viewer and I'm not convinced we'd get any better information here)

What about dumping the packet data and result codes when receiving a "Length Mismatch" error so we can see what is being sent and maybe figure out where the gap is?

**Comment by daleglass** [comment] 2020-05-17 11:53
Okay, let's look at the code here.

```
void AudioInputDeviceList::onPeakValueListChanged(const QList<float>& peakValueList) {
    assert(_mode == QAudio::AudioInput);

    if (peakValueList.length() != rowCount()) {
        qWarning() << "AudioDeviceList" << __FUNCTION__ << "length mismatch";
    }
```

`rowCount()` is the count of audio devices. Okay, so all this warning seems to tell us is that the audio devices list is empty, for some reason.

One prospective place where to look seems to be `AudioDeviceList::onDevicesChanged`. Based on a quick look, there doesn't seem to be anything wrong there, but it could use some debug output so that we can tell if it's being called at all.

So perhaps is that the problem is it's not getting called when it should be. It's called from AudioDevices::onDevicesChanged, which calls them always.

This is called as a handler for AudioClient::devicesChanged, which is emitted only in AudioClient::checkDevices().

That one looks interesting, _checkDevicesMutex, _hmdNameLock and _deviceMutex are taken.

Since the problem is intermittent, it could well have to do with locking. 
* `_checkDevicesMutex` is only taken there, and in AudioClient::stop. Probably not that.
* `_hmdNameLock` is a RW lock, taken for reading. It's taken for writing in AudioClient::setHmdAudioName, which looks trivial, and the other places where it's locked for reading seem trivial too. Probably not this either.
* `_deviceMutex` seems like it could be promising. It's taken, and then `emit devicesChanged(QAudio::AudioInput, _inputDevices)` is called with the lock held.

I think this last one is promising. There's quite a lot of stuff going on with this lock held in:
* getAvailableDevices
* AudioClient::checkDevices
* AudioClient::switchInputToAudioDevice
* AudioClient::switchOutputToAudioDevice

@odysseus654 I think minidumping this could actually be a great idea. There could well be a threading issue here.

@NathanAdored  Could you post a full log made when the problem occurs?

**Comment by odysseus654** [comment] 2020-05-17 20:08
The biggest hole I see potentially in the code is that AudioDevices doesn't retrieve the list of audio devices when it is constructed, only when that list changes after construction.  This leads into the potential of a race condition (which is possibly technically a threading issue).

The patch I highlighted at https://github.com/kasenvr/project-athena/commit/4f009d884f963a2949c80995ca28f2db668d60b9 seems to add a check to only look for (and notify about) changes if someone is listening to see them.  This does seem like it would work around this but feels a bit weak of a solution as it assumes there is exactly one listener -- if I were around for this commit I would have suggested replacing this change with an explicit pull in AudioDevices after the connect() line executed (unless there's a strong reason why we can't do a pull on this).

**Comment by odysseus654** [comment] 2020-05-17 20:13
Also I've build this Windows 10 dev build from my workstation with additional log rules that should help us see the list of audio devices and whether AudioDeviceList::onDevicesChanged ever gets called: https://odys-asset.s3.amazonaws.com/vircadia-pr355-unofficial.zip

**Comment by daleglass** [comment] 2020-06-06 18:32
Needs retesting in K3

**Comment by kasenvr** [comment] 2020-06-13 18:26
Seems to have been fixed in the latest releases, we can reopen if someone reports this issue again.

**Closed by kasenvr** 2020-06-13 18:26 UTC
Labels: bug, needs retesting (QA)
